/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.ns.thongtinphanhoi.dao.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the ChiTietThongTinPhanHoi service. Represents a row in the &quot;ws_chitiet_thongtin_phanhoi&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.dtt.ns.thongtinphanhoi.dao.model.impl.ChiTietThongTinPhanHoiModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.dtt.ns.thongtinphanhoi.dao.model.impl.ChiTietThongTinPhanHoiImpl}.
 * </p>
 *
 * @author tubq
 * @see ChiTietThongTinPhanHoi
 * @see vn.dtt.ns.thongtinphanhoi.dao.model.impl.ChiTietThongTinPhanHoiImpl
 * @see vn.dtt.ns.thongtinphanhoi.dao.model.impl.ChiTietThongTinPhanHoiModelImpl
 * @generated
 */
public interface ChiTietThongTinPhanHoiModel extends BaseModel<ChiTietThongTinPhanHoi> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a chi tiet thong tin phan hoi model instance should use the {@link ChiTietThongTinPhanHoi} interface instead.
	 */

	/**
	 * Returns the primary key of this chi tiet thong tin phan hoi.
	 *
	 * @return the primary key of this chi tiet thong tin phan hoi
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this chi tiet thong tin phan hoi.
	 *
	 * @param primaryKey the primary key of this chi tiet thong tin phan hoi
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this chi tiet thong tin phan hoi.
	 *
	 * @return the ID of this chi tiet thong tin phan hoi
	 */
	public long getId();

	/**
	 * Sets the ID of this chi tiet thong tin phan hoi.
	 *
	 * @param id the ID of this chi tiet thong tin phan hoi
	 */
	public void setId(long id);

	/**
	 * Returns the thong tin phan hoi ID of this chi tiet thong tin phan hoi.
	 *
	 * @return the thong tin phan hoi ID of this chi tiet thong tin phan hoi
	 */
	public long getThongTinPhanHoiId();

	/**
	 * Sets the thong tin phan hoi ID of this chi tiet thong tin phan hoi.
	 *
	 * @param thongTinPhanHoiId the thong tin phan hoi ID of this chi tiet thong tin phan hoi
	 */
	public void setThongTinPhanHoiId(long thongTinPhanHoiId);

	/**
	 * Returns the ma tram cap nuoc of this chi tiet thong tin phan hoi.
	 *
	 * @return the ma tram cap nuoc of this chi tiet thong tin phan hoi
	 */
	@AutoEscape
	public String getMaTramCapNuoc();

	/**
	 * Sets the ma tram cap nuoc of this chi tiet thong tin phan hoi.
	 *
	 * @param maTramCapNuoc the ma tram cap nuoc of this chi tiet thong tin phan hoi
	 */
	public void setMaTramCapNuoc(String maTramCapNuoc);

	/**
	 * Returns the noi dung khac nuoc of this chi tiet thong tin phan hoi.
	 *
	 * @return the noi dung khac nuoc of this chi tiet thong tin phan hoi
	 */
	@AutoEscape
	public String getNoiDungKhacNuoc();

	/**
	 * Sets the noi dung khac nuoc of this chi tiet thong tin phan hoi.
	 *
	 * @param noiDungKhacNuoc the noi dung khac nuoc of this chi tiet thong tin phan hoi
	 */
	public void setNoiDungKhacNuoc(String noiDungKhacNuoc);

	/**
	 * Returns the noi dung khac ve sinh of this chi tiet thong tin phan hoi.
	 *
	 * @return the noi dung khac ve sinh of this chi tiet thong tin phan hoi
	 */
	@AutoEscape
	public String getNoiDungKhacVeSinh();

	/**
	 * Sets the noi dung khac ve sinh of this chi tiet thong tin phan hoi.
	 *
	 * @param noiDungKhacVeSinh the noi dung khac ve sinh of this chi tiet thong tin phan hoi
	 */
	public void setNoiDungKhacVeSinh(String noiDungKhacVeSinh);

	/**
	 * Returns the ma thong tin phan anh of this chi tiet thong tin phan hoi.
	 *
	 * @return the ma thong tin phan anh of this chi tiet thong tin phan hoi
	 */
	@AutoEscape
	public String getMaThongTinPhanAnh();

	/**
	 * Sets the ma thong tin phan anh of this chi tiet thong tin phan hoi.
	 *
	 * @param maThongTinPhanAnh the ma thong tin phan anh of this chi tiet thong tin phan hoi
	 */
	public void setMaThongTinPhanAnh(String maThongTinPhanAnh);

	/**
	 * Returns the yeu cau giai trinh ID of this chi tiet thong tin phan hoi.
	 *
	 * @return the yeu cau giai trinh ID of this chi tiet thong tin phan hoi
	 */
	public long getYeuCauGiaiTrinhId();

	/**
	 * Sets the yeu cau giai trinh ID of this chi tiet thong tin phan hoi.
	 *
	 * @param yeuCauGiaiTrinhId the yeu cau giai trinh ID of this chi tiet thong tin phan hoi
	 */
	public void setYeuCauGiaiTrinhId(long yeuCauGiaiTrinhId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ChiTietThongTinPhanHoi chiTietThongTinPhanHoi);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ChiTietThongTinPhanHoi> toCacheModel();

	@Override
	public ChiTietThongTinPhanHoi toEscapedModel();

	@Override
	public ChiTietThongTinPhanHoi toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}