/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.ns.thongtinphanhoi.dao.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the TopicDetails service. Represents a row in the &quot;thongtinphanhoi_TopicDetails&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.dtt.ns.thongtinphanhoi.dao.model.impl.TopicDetailsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.dtt.ns.thongtinphanhoi.dao.model.impl.TopicDetailsImpl}.
 * </p>
 *
 * @author tubq
 * @see TopicDetails
 * @see vn.dtt.ns.thongtinphanhoi.dao.model.impl.TopicDetailsImpl
 * @see vn.dtt.ns.thongtinphanhoi.dao.model.impl.TopicDetailsModelImpl
 * @generated
 */
public interface TopicDetailsModel extends BaseModel<TopicDetails> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a topic details model instance should use the {@link TopicDetails} interface instead.
	 */

	/**
	 * Returns the primary key of this topic details.
	 *
	 * @return the primary key of this topic details
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this topic details.
	 *
	 * @param primaryKey the primary key of this topic details
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this topic details.
	 *
	 * @return the ID of this topic details
	 */
	public long getId();

	/**
	 * Sets the ID of this topic details.
	 *
	 * @param id the ID of this topic details
	 */
	public void setId(long id);

	/**
	 * Returns the so dien thoai of this topic details.
	 *
	 * @return the so dien thoai of this topic details
	 */
	@AutoEscape
	public String getSoDienThoai();

	/**
	 * Sets the so dien thoai of this topic details.
	 *
	 * @param soDienThoai the so dien thoai of this topic details
	 */
	public void setSoDienThoai(String soDienThoai);

	/**
	 * Returns the thoi gian goi of this topic details.
	 *
	 * @return the thoi gian goi of this topic details
	 */
	public Date getThoiGianGoi();

	/**
	 * Sets the thoi gian goi of this topic details.
	 *
	 * @param thoiGianGoi the thoi gian goi of this topic details
	 */
	public void setThoiGianGoi(Date thoiGianGoi);

	/**
	 * Returns the tong dai of this topic details.
	 *
	 * @return the tong dai of this topic details
	 */
	public int getTongDai();

	/**
	 * Sets the tong dai of this topic details.
	 *
	 * @param tongDai the tong dai of this topic details
	 */
	public void setTongDai(int tongDai);

	/**
	 * Returns the ma tinh of this topic details.
	 *
	 * @return the ma tinh of this topic details
	 */
	@AutoEscape
	public String getMaTinh();

	/**
	 * Sets the ma tinh of this topic details.
	 *
	 * @param maTinh the ma tinh of this topic details
	 */
	public void setMaTinh(String maTinh);

	/**
	 * Returns the ma huyen of this topic details.
	 *
	 * @return the ma huyen of this topic details
	 */
	@AutoEscape
	public String getMaHuyen();

	/**
	 * Sets the ma huyen of this topic details.
	 *
	 * @param maHuyen the ma huyen of this topic details
	 */
	public void setMaHuyen(String maHuyen);

	/**
	 * Returns the ma xa of this topic details.
	 *
	 * @return the ma xa of this topic details
	 */
	@AutoEscape
	public String getMaXa();

	/**
	 * Sets the ma xa of this topic details.
	 *
	 * @param maXa the ma xa of this topic details
	 */
	public void setMaXa(String maXa);

	/**
	 * Returns the ma tram cap nuoc of this topic details.
	 *
	 * @return the ma tram cap nuoc of this topic details
	 */
	@AutoEscape
	public String getMaTramCapNuoc();

	/**
	 * Sets the ma tram cap nuoc of this topic details.
	 *
	 * @param maTramCapNuoc the ma tram cap nuoc of this topic details
	 */
	public void setMaTramCapNuoc(String maTramCapNuoc);

	/**
	 * Returns the ma thong tin phan anh of this topic details.
	 *
	 * @return the ma thong tin phan anh of this topic details
	 */
	@AutoEscape
	public String getMaThongTinPhanAnh();

	/**
	 * Sets the ma thong tin phan anh of this topic details.
	 *
	 * @param maThongTinPhanAnh the ma thong tin phan anh of this topic details
	 */
	public void setMaThongTinPhanAnh(String maThongTinPhanAnh);

	/**
	 * Returns the noi dung khac nuoc of this topic details.
	 *
	 * @return the noi dung khac nuoc of this topic details
	 */
	@AutoEscape
	public String getNoiDungKhacNuoc();

	/**
	 * Sets the noi dung khac nuoc of this topic details.
	 *
	 * @param noiDungKhacNuoc the noi dung khac nuoc of this topic details
	 */
	public void setNoiDungKhacNuoc(String noiDungKhacNuoc);

	/**
	 * Returns the noi dung khac vesinh of this topic details.
	 *
	 * @return the noi dung khac vesinh of this topic details
	 */
	@AutoEscape
	public String getNoiDungKhacVesinh();

	/**
	 * Sets the noi dung khac vesinh of this topic details.
	 *
	 * @param noiDungKhacVesinh the noi dung khac vesinh of this topic details
	 */
	public void setNoiDungKhacVesinh(String noiDungKhacVesinh);

	/**
	 * Returns the yeu cau giai trinh ID of this topic details.
	 *
	 * @return the yeu cau giai trinh ID of this topic details
	 */
	public long getYeuCauGiaiTrinhId();

	/**
	 * Sets the yeu cau giai trinh ID of this topic details.
	 *
	 * @param yeuCauGiaiTrinhId the yeu cau giai trinh ID of this topic details
	 */
	public void setYeuCauGiaiTrinhId(long yeuCauGiaiTrinhId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(TopicDetails topicDetails);

	@Override
	public int hashCode();

	@Override
	public CacheModel<TopicDetails> toCacheModel();

	@Override
	public TopicDetails toEscapedModel();

	@Override
	public TopicDetails toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}