/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.ns.thongtinphanhoi.dao.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the TopicPhanHoi service. Represents a row in the &quot;thongtinphanhoi_TopicPhanHoi&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.dtt.ns.thongtinphanhoi.dao.model.impl.TopicPhanHoiModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.dtt.ns.thongtinphanhoi.dao.model.impl.TopicPhanHoiImpl}.
 * </p>
 *
 * @author tubq
 * @see TopicPhanHoi
 * @see vn.dtt.ns.thongtinphanhoi.dao.model.impl.TopicPhanHoiImpl
 * @see vn.dtt.ns.thongtinphanhoi.dao.model.impl.TopicPhanHoiModelImpl
 * @generated
 */
public interface TopicPhanHoiModel extends BaseModel<TopicPhanHoi> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a topic phan hoi model instance should use the {@link TopicPhanHoi} interface instead.
	 */

	/**
	 * Returns the primary key of this topic phan hoi.
	 *
	 * @return the primary key of this topic phan hoi
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this topic phan hoi.
	 *
	 * @param primaryKey the primary key of this topic phan hoi
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the topic code of this topic phan hoi.
	 *
	 * @return the topic code of this topic phan hoi
	 */
	@AutoEscape
	public String getTopicCode();

	/**
	 * Sets the topic code of this topic phan hoi.
	 *
	 * @param topicCode the topic code of this topic phan hoi
	 */
	public void setTopicCode(String topicCode);

	/**
	 * Returns the ma tinh of this topic phan hoi.
	 *
	 * @return the ma tinh of this topic phan hoi
	 */
	@AutoEscape
	public String getMaTinh();

	/**
	 * Sets the ma tinh of this topic phan hoi.
	 *
	 * @param maTinh the ma tinh of this topic phan hoi
	 */
	public void setMaTinh(String maTinh);

	/**
	 * Returns the ma huyen of this topic phan hoi.
	 *
	 * @return the ma huyen of this topic phan hoi
	 */
	@AutoEscape
	public String getMaHuyen();

	/**
	 * Sets the ma huyen of this topic phan hoi.
	 *
	 * @param maHuyen the ma huyen of this topic phan hoi
	 */
	public void setMaHuyen(String maHuyen);

	/**
	 * Returns the ma xa of this topic phan hoi.
	 *
	 * @return the ma xa of this topic phan hoi
	 */
	@AutoEscape
	public String getMaXa();

	/**
	 * Sets the ma xa of this topic phan hoi.
	 *
	 * @param maXa the ma xa of this topic phan hoi
	 */
	public void setMaXa(String maXa);

	/**
	 * Returns the topic name of this topic phan hoi.
	 *
	 * @return the topic name of this topic phan hoi
	 */
	@AutoEscape
	public String getTopicName();

	/**
	 * Sets the topic name of this topic phan hoi.
	 *
	 * @param topicName the topic name of this topic phan hoi
	 */
	public void setTopicName(String topicName);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(TopicPhanHoi topicPhanHoi);

	@Override
	public int hashCode();

	@Override
	public CacheModel<TopicPhanHoi> toCacheModel();

	@Override
	public TopicPhanHoi toEscapedModel();

	@Override
	public TopicPhanHoi toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}